language: java
jdk:
- oraclejdk8
sudo: false
install: true
script:
- cd csye6225-spring-boot-starter-webapp-master
- "./gradlew build"


after_success:
  - pwd
  - mkdir codedeploy
  - zip -r csye6225-spring-boot-starter-webapp-master.zip build/libs/ROOT.war appspec.yml ./restartTomcat.sh
  - ls -al
  - mv csye6225-spring-boot-starter-webapp-master.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..
  - pwd
  
  

deploy:
  - provider: s3
    access_key_id: AKIAJZP76MZEPNFIHF6A
    secret_access_key: 
      secure:  "cBGIrWPIWLYO/W7+y91M3lEO3gLW1VLHo3An5GjnGpdsbPm/Qg8zuyRRVvfRm0aaLxeWpBrd6oqJOUpRZcL9qsJykITf19VyHGynWfV6YsY6DA+3Kpgo4NCxk30F3jKNzk3OxPHOYShHEVUCMTsB6bwWyLfX3kXzipb122PN0EyWZF8QqQIbtCPGnamOBRUK5EL35+b1ZXoF4Zdh6T2IuavOxkeAyD83rbADm45MNlY0XVZE1HkoOzS+NC2HJFmSuKVLyD3Ajx2k2NHUbPzckHwkmnptFz8z0sl5jajIjZXzqpOKHwaGtE90L7FIVOhna0EYBDWN60Urh7NQUkggbV6IwtrpsD48tVhZ8yKyeuCBn39D6m9eLBPHPzM16bW6M67DksHSg/xp+O+VrbnwHbNCgIUyaVjTN5aBTyVEYltUD33mRiaKNiom2xtchaP65uHHfjVsEsWggx8U50M7M5fTRs1PfX5iFP9UPjnwkkfTKR7pPmF9jX/q7Lobbqi9jD7zviqUOP+1OO+4XX1TPI+JHgfTkbKGzdqqyLeuZT7N1tvGv55BSCqhd1jInPeR8wIW+qAhXn2cH7I63eqq2cvx3QR48nAeCMDZ8Goku8I83ZrbHo7JiXH6R1ElQxRAVRfiNpyMlSxkdBlOB/iaNzFlKm/tthj9D6MPy/o0KeM="
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-patilm.me
    region: us-east-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAJZP76MZEPNFIHF6A
    bucket: code-deploy.csye6225.com-fall2017-patilm.me
    key: csye6225-spring-boot-starter-webapp-master.zip
    bundle_type: zip
    application: SimpleJavaProject
    deployment_group: SimpleJavaProject
    region: us-east-1
    secret_access_key:
      secure:  "cBGIrWPIWLYO/W7+y91M3lEO3gLW1VLHo3An5GjnGpdsbPm/Qg8zuyRRVvfRm0aaLxeWpBrd6oqJOUpRZcL9qsJykITf19VyHGynWfV6YsY6DA+3Kpgo4NCxk30F3jKNzk3OxPHOYShHEVUCMTsB6bwWyLfX3kXzipb122PN0EyWZF8QqQIbtCPGnamOBRUK5EL35+b1ZXoF4Zdh6T2IuavOxkeAyD83rbADm45MNlY0XVZE1HkoOzS+NC2HJFmSuKVLyD3Ajx2k2NHUbPzckHwkmnptFz8z0sl5jajIjZXzqpOKHwaGtE90L7FIVOhna0EYBDWN60Urh7NQUkggbV6IwtrpsD48tVhZ8yKyeuCBn39D6m9eLBPHPzM16bW6M67DksHSg/xp+O+VrbnwHbNCgIUyaVjTN5aBTyVEYltUD33mRiaKNiom2xtchaP65uHHfjVsEsWggx8U50M7M5fTRs1PfX5iFP9UPjnwkkfTKR7pPmF9jX/q7Lobbqi9jD7zviqUOP+1OO+4XX1TPI+JHgfTkbKGzdqqyLeuZT7N1tvGv55BSCqhd1jInPeR8wIW+qAhXn2cH7I63eqq2cvx3QR48nAeCMDZ8Goku8I83ZrbHo7JiXH6R1ElQxRAVRfiNpyMlSxkdBlOB/iaNzFlKm/tthj9D6MPy/o0KeM="
    wait-until-deployed: true


notifications:
  email:
    recipients:
    - shetye.v@husky.neu.edu
    - patil.m@husky.neu.edu
    - khedekar.p@husky.neu.edu
    - takekar.a@husky.neu.edu
    on_success: always

