#!/bin/bash
# Mihir Patil,     001220443, patil.m@husky.neu.edu
# Vivek Shetye,    001237626, shetye.v@husky.neu.edu
# Pushkar Khedekar,001225610, khedekar.p@husky.neu.edu
# Atul Takekar,    001220479, takekar.a@husky.neu.edu
#

language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build


notifications:
  email:
    recipients:
      - shetye.v@husky.neu.edu
      - patil.m@husky.neu.edu
      - khedekar.p@husky.neu.edu
      - takekar.a@husky.neu.edu
    on_success: always



